/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthPrefs: typeof import('./components/AuthPrefs.vue')['default']
    ChangePasswordCard: typeof import('./components/ChangePasswordCard.vue')['default']
    DashboardCharts: typeof import('./components/DashboardCharts.vue')['default']
    DashboardWelcome: typeof import('./components/DashboardWelcome.vue')['default']
    ElAlert: typeof import('element-plus/es/components/alert/index.mjs')['ElAlert']
    ElAvatar: typeof import('element-plus/es/components/avatar/index.mjs')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es/components/breadcrumb/index.mjs')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es/components/breadcrumb/index.mjs')['ElBreadcrumbItem']
    ElCard: typeof import('element-plus/es/components/card/index.mjs')['ElCard']
    ElCol: typeof import('element-plus/es/components/col/index.mjs')['ElCol']
    ElConfigProvider: typeof import('element-plus/es/components/config-provider/index.mjs')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es/components/date-picker/index.mjs')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es/components/descriptions/index.mjs')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es/components/descriptions/index.mjs')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es/components/dialog/index.mjs')['ElDialog']
    ElDivider: typeof import('element-plus/es/components/divider/index.mjs')['ElDivider']
    ElDropdown: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es/components/empty/index.mjs')['ElEmpty']
    ElForm: typeof import('element-plus/es/components/form/index.mjs')['ElForm']
    ElFormItem: typeof import('element-plus/es/components/form/index.mjs')['ElFormItem']
    ElIcon: typeof import('element-plus/es/components/icon/index.mjs')['ElIcon']
    ElInput: typeof import('element-plus/es/components/input/index.mjs')['ElInput']
    ElInputNumber: typeof import('element-plus/es/components/input-number/index.mjs')['ElInputNumber']
    ElMenu: typeof import('element-plus/es/components/menu/index.mjs')['ElMenu']
    ElMenuItem: typeof import('element-plus/es/components/menu/index.mjs')['ElMenuItem']
    ElOption: typeof import('element-plus/es/components/select/index.mjs')['ElOption']
    ElPagination: typeof import('element-plus/es/components/pagination/index.mjs')['ElPagination']
    ElRadio: typeof import('element-plus/es/components/radio/index.mjs')['ElRadio']
    ElRadioButton: typeof import('element-plus/es/components/radio/index.mjs')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es/components/radio/index.mjs')['ElRadioGroup']
    ElRow: typeof import('element-plus/es/components/row/index.mjs')['ElRow']
    ElSelect: typeof import('element-plus/es/components/select/index.mjs')['ElSelect']
    ElSubMenu: typeof import('element-plus/es/components/menu/index.mjs')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es/components/switch/index.mjs')['ElSwitch']
    ElTable: typeof import('element-plus/es/components/table/index.mjs')['ElTable']
    ElTableColumn: typeof import('element-plus/es/components/table/index.mjs')['ElTableColumn']
    ElTag: typeof import('element-plus/es/components/tag/index.mjs')['ElTag']
    ElTooltip: typeof import('element-plus/es/components/tooltip/index.mjs')['ElTooltip']
    GlassSegmented: typeof import('./components/GlassSegmented.vue')['default']
    GlassSkeleton: typeof import('./components/GlassSkeleton.vue')['default']
    InspectionCompleteForm: typeof import('./components/InspectionCompleteForm.vue')['default']
    InspectionForm: typeof import('./components/InspectionForm.vue')['default']
    InspectionReviewForm: typeof import('./components/InspectionReviewForm.vue')['default']
    LiquidGlassButtons: typeof import('./components/LiquidGlassButtons.vue')['default']
    MfaSettingsCard: typeof import('./components/MfaSettingsCard.vue')['default']
    PasswordStrengthMeter: typeof import('./components/PasswordStrengthMeter.vue')['default']
    PermissionModuleCard: typeof import('./components/PermissionModuleCard.vue')['default']
    RecentAlarmsCard: typeof import('./components/RecentAlarmsCard.vue')['default']
    RegisterSummary: typeof import('./components/RegisterSummary.vue')['default']
    RoleFormDialog: typeof import('./components/RoleFormDialog.vue')['default']
    RoleListPanel: typeof import('./components/RoleListPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionManager: typeof import('./components/SessionManager.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es/components/loading/index.mjs')['ElLoadingDirective']
  }
}
